### ISSUE TITLE
Some API endpoints to consider

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#19]
I figured we should keep track of some API endpoints that aren't currently part of the API but are needed in the frontend so you guys know what's still missing:

### GET all _Events_ assigned to a specific _Event Manager_
- need this to display all the events that are managed by a specific event manager so he can see how many tickets are sold and stuff like that
- **args**: id OR email OR username for the event manager _(I think email or username is the best since I can save it in local storage on login, what do you think?)_
- [x] done

### GET all _Events_ created by a specific _Event Creator_
- need this to display all the events that are created by an Event creator so he can see / update / delete his events
- **args**: id OR email OR username for the event creator 
- [x] done

### GET all _Activities_ regarding events where a specific _Event Manager_ is assigned to 
- I thought it would be cool to have a page for an Event Manager where he can see like the last 10, 20 or whatever ticket purchases for events that he organises. 
- **args**: id OR email OR username for the event manager
- If it is too complex to keep track of activities inside the database we could just give him a pop up notification when a ticket purchase is made 
- [ ] done

### GET all _Event Managers_ available
- since the event creators are the ones creating the events, they need to assign the Event Managers the the event they create. I think it makes sense to implement a dropdown menu where they can choose an Event Manager
- Im open for other ideas since I don't know If it is intended that Event Creators can assign the Event Managers or if they are just chosen randomly 
- [x] done

### DB considerations
- the first 2 endpoints require each event to reference an event manager aswell as an event creator. It would make sense to have an ER model for the database, see #16

**Comment by 53845714nF** [comment]
Was sind eigentlich Activities?

**Comment by arneallwardt** [comment]
> Was sind eigentlich Activities?

<img width="617" alt="Screenshot 2024-12-15 at 21 06 28" src="https://github.com/user-attachments/assets/8c95a5fa-1901-4735-8b1b-2138e010c7e6" />

sowas. Wir hatten überlegt ob wir das einfach als kleine Toast Message machen aber ich finds schon cooler wenn man das mal übersichtlich sehen kann. Hat die andere Gruppe meines Wissens nach auch so gemacht

**Comment by 53845714nF** [comment]
Ist das ein muss? Würde mich jetzt eher auf die muss Aufgaben konzentrieren. Also Tickets und Gutscheine.

**Comment by arneallwardt** [comment]
Ich glaube Frau Schmidt fänd es schon nice wenn das drin ist. Zumindest hat sie beim ATAM so gewirkt als wir drüber geredet haben.

**Comment by LuchsHub** [comment]
For the third item, I propose adding a "purchase_date" to tickets. When an event manager visits the "activities" site, the last 25 (defined by param) events for which he is assigned as manager are listed.
