### ISSUE TITLE
Make role of the current user available in frontend

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#22]
At the moment I can't retrieve the role of the logged in user from the backend, but I need to store it somewhere in the frontend. Therefore, I need an endpoint to get the role of the user

Ideally, I can store the role after login, which means it should be returned by `api/v1/login/access-token`. 

Alternatively, I could get the role manually by validating the token using `api/v1/login/test-token`, but then the role of the user has to be returned there

**Comment by 53845714nF** [comment]
Hole es dir bitte aus `api/v1/login/test-token` oder `/api/v1/users/me`. PR kommt.
