### ISSUE TITLE
Kunden müssen Tickets kaufen können

### ISSUE THREAD

**Issue by 53845714nF** [53845714nF/EventTom#35]
Bei den Events musst du wahrscheinlich noch ein verkauftes Ticket oder sowas einfügen.

Und dann halt gucken, was noch gebraucht wird. Denke, das werden noch mal einige Models für die Tickets/Verkauf.

**Comment by LuchsHub** [comment]
The backend attribute is there now. Let's see what other routes we're gonna need later on, for example for using vouchers for purchases.
