### ISSUE TITLE
Add `role = customer` for `user_type = customer`?

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#38]
At the moment customers have no role, but I think it would be beneficial to let customers have the role `customer`. What do you think? Or is this not possible in the backend?

reference: 

<img width="1760" alt="Screenshot 2024-12-19 at 13 43 15" src="https://github.com/user-attachments/assets/c70d6ec8-8075-4406-818e-73a6de38c842" />

**Comment by 53845714nF** [comment]
Kann das `user_type` aus der API raus?

**Comment by arneallwardt** [comment]
Gerne, ist ja sonst nur reduntant

**Comment by LuchsHub** [comment]
`user_type` no longer exists, every user possesses a role now.
