### ISSUE TITLE
Voucher needs an attribute `code`

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#39]
at the moment voucher has following attributes:
- `id`
- `owner_id`
- `amount`

But it needs some kind of key to be easily identifiable by the customer. I think adding an attribute `code` or something like that would be a good idea so that the customer can enter the `code` at checkout instead of the `id` (`id` would be something like "3fa85f64-5717-4562-b3fc-2c963f66afa6" whereas `code` can be something like "Arne20")

**Comment by 53845714nF** [comment]
Das ist ja dann ein Rabattcode und kein personalisierter Gutschein.
Kunden können diese Gutscheine nur bekommen und nicht anfordern.

**Comment by arneallwardt** [comment]
Schon klar. Aber die Kunden müssen die ja auch irgendwie einlösen können. Stell dir vor du hast 2 Gutscheine mit unterschiedlichen Rabatten, dann möchtest du ja den besten auswählen können und dabei beim checkout nicht unbedingt sone ewig lange id eingeben

**Comment by 53845714nF** [comment]
Also eine Art Namen bloß, dass wir es code nennen? Das müsste gehen.
