### ISSUE TITLE
Event needs some kind of attribute to keep track of sold tickets

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#43]
We need this to display the amount of tickets sold to the EventManager.

I have 2 ways in mind:

1) add `available_tickets` (the amount of tickets that are currently available, starting at `count`) and count down from there

2) add `tickets_sold` (the amount that of tickets that are currently sold, starting at zero) and count up from there

You can decide which way is more convenient for you to implement or do it a different way if you want

**Comment by 53845714nF** [comment]
This Issue is hard, combined with #35. We have the Count (available_tickets) should be fixed. The `tickets_sold` is needed.
I think we should have also a Table where User and bought Event is saved.

Model Ticket:
id: UUID
event: Event
user: UUID  

@LuchsHub can you do that?

**Comment by LuchsHub** [comment]
I'm on it.

**Comment by LuchsHub** [comment]
This issue is handled with PR #49.
