### ISSUE TITLE
Why is request body of `api/v1/login/access-token` type `application/x-www-form-urlencoded`?

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#44]
As title says, the request body for `api/v1/login/access-token` is type `application/x-www-form-urlencoded`:

<img width="1806" alt="Screenshot 2024-12-22 at 11 05 57" src="https://github.com/user-attachments/assets/66fa075b-ba80-4d02-bd6a-53488c957443" />

This isn't necessarily an issue, but the request body for every other endpoint is type `application/json`:

<img width="1790" alt="Screenshot 2024-12-22 at 11 06 20" src="https://github.com/user-attachments/assets/e4086dd6-defd-492b-afe3-70986d959532" />

Is there a reason for that? If not, making `api/v1/login/access-token` also type `application/json` would make the code a bit more readable

**Comment by 53845714nF** [comment]
All of this comes from the Template, you can ask this question here: [Fastapi Template discussions](https://github.com/fastapi/full-stack-fastapi-template/discussions)

**Comment by arneallwardt** [comment]
So is this fixable or not?

**Comment by 53845714nF** [comment]
I don't really want to touch it as long as it works.

**Comment by LuchsHub** [comment]
Not planned in the scope of this project.
