### ISSUE TITLE
**full_name** oder **username** als Attribut für den Namen des Users

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#5]
*/api/v1/users/signup* nutzt **full_name** als Attribut für den Namen des Users.
*/api/v1/login/access-token* nutzt **username** als Attribut für den Namen des Users.

Soll das so oder wird das noch geändert? Und wenn ja, welche Bezeichnung ist die richtige?

**Comment by 53845714nF** [comment]
Ich werde Dienstag mal gucken, dass ich, das einheitlich mache.

**Comment by 53845714nF** [comment]
Ich glaube es ist noch wilder das Username ist die E-mail.

**Comment by 53845714nF** [comment]
Ich denke ich kann das zu machen.
