### ISSUE TITLE
Add `event_title` attribute to ticket

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#57]
At the moment when retrieving the tickets for a user I can only access `event_id`, but I need to display the name of the event in the frontend. I could fetch all events and filter them manually but it would be easier if you would add `event_title` as an attribute to the ticket model. Is this possible? @LuchsHub @53845714nF 

for reference:

<img width="1217" alt="Screenshot 2024-12-29 at 11 07 17" src="https://github.com/user-attachments/assets/89ffdac3-c7a2-4ff7-9de7-841cf1f90a25" />

**Comment by LuchsHub** [comment]
I think this should be solved with a SQL Join, not with a redundant attribute. I’ll update the route to deliver kot only the ticket details but also the corresponding event details.
