### ISSUE TITLE
Should customer be able to delete vouchers?

### ISSUE THREAD

**Issue by arneallwardt** [53845714nF/EventTom#59]
If a voucher is applied to a ticket purchase, should it be deleted afterwards? I think so, but this would require that a customer can delete vouchers which is not the case at the moment

<img width="1226" alt="Screenshot 2024-12-30 at 09 21 15" src="https://github.com/user-attachments/assets/f22e57d2-60a0-4e8a-8716-6d462a29630d" />

**Comment by LuchsHub** [comment]
Vouchers are automatically deleted after being used in a ticket purchase, see

https://github.com/53845714nF/EventTom/blob/main/backend/app/api/routes/tickets.py

**Comment by arneallwardt** [comment]
Thanks, my branch wasn't up to date when I tested it
